# general
dataset_name: "bcic2a"  # LOSO: bcic2a_loso
subject_ids: "all"  # either "all" or integer
max_epochs: 500  # LOSO: 125
seed: 0

# preprocessing
preprocessing:
  sfreq: 250
  low_cut: 0
  high_cut: 40
  start: 0.5
  stop: 0.0  # 4 second trial -> [0.5, 4.0]
  z_scale: True
  batch_size: 64

# model
model: "ShallowNet"
model_kwargs:
  in_channels: 22
  n_classes: 4
  input_window_samples: 875
  n_filters_time: 40
  filter_time_length: 25
  pool_time_length: 75
  pool_time_stride: 15
  drop_prob: 0.5
  lr: 0.001
  weight_decay: 0.0
  optimizer: "adam"
  scheduler: False