# general
dataset_name: "bcic3"  # LOSO: bcic3_loso
subject_ids: "all"  # either "all" or integer
max_epochs: 2000  # LOSO: 250
seed: 0

# preprocessing
preprocessing:
  sfreq: 100
  low_cut: 4
  high_cut: 40
  channel_selection: True
  start: 0.0
  stop: 0.0
  z_scale: True
  batch_size: 28

# model
model: "EEGConformer"
model_kwargs:
  in_channels: 3
  embedding_size: 40
  depth: 6
  n_classes: 2
  input_size_cls: 680
  interaug: True
  lr: 0.0002
  beta_1: 0.5
  weight_decay: 0.0
  optimizer: "adam"
  scheduler: True
  warmup_epochs: 20  # LOSO: 3
  label_smoothing: 0.0