# general
dataset_name: "bcic3"  # LOSO: bcic3_loso
subject_ids: "all"  # either "all" or integer
max_epochs: 500  # LOSO: 125
seed: 0

# preprocessing
preprocessing:
  sfreq: 100
  low_cut: 0
  high_cut: 40
  channel_selection: True
  start: 0.5
  stop: -1.0  # 3.5 second trial -> [0.5, 2.5]
  z_scale: True
  batch_size: 28

# model
model: "EEGNet"
model_kwargs:
  n_classes: 2
  in_channels: 3
  input_window_samples: 200
  F1: 8
  D: 2
  F2: 16  # F1 * D
  drop_prob: 0.5  # LOSO: 0.25
  kernel_length: 32
  simplify: False
  projector: False
  pool_time_length: 4
  pool_time_stride: 4
  kernel_length_dw_sep: 16
  lr: 0.001
  weight_decay: 0.0
  optimizer: "adam"
  scheduler: False
  warmup_epochs: 20  # LOSO: 3