# general
dataset_name: "hgd"  # LOSO: hgd_loso
subject_ids: "all"  # either "all" or integer
max_epochs: 1000  # LOSO: 77
seed: 0

# preprocessing
preprocessing:
  sfreq: 128
  low_cut: 4
  high_cut: null
  start: 0.5
  stop: -1.5  # 4 second trial -> [0.5, 2.5]
  remove_artifacts: True
  z_scale: True
  batch_size: 64

# model
model: "EEGNet"
model_kwargs:
  n_classes: 4
  in_channels: 44
  input_window_samples: 256
  F1: 8
  D: 2
  F2: 16  # F1 * D
  drop_prob: 0.5  # LOSO: 0.25
  kernel_length: 32
  pool_time_length: 4
  pool_time_stride: 4
  kernel_length_dw_sep: 16
  lr: 0.001
  weight_decay: 0.0
  optimizer: "adam"
  scheduler: False